version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/api

  migrate:
    cmds:
      - go run ./cmd/api migrate

  wire:
    cmds:
      - go run -mod=mod github.com/google/wire/cmd/wire ./internal/di

  wire-check:
    cmds:
      - task wire
      - git diff --exit-code internal/di/wire_gen.go

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - go vet ./...

  ci:
    cmds:
      - task wire-check
      - task lint
      - task test

  docker-up:
    cmds:
      - docker compose up --build -d

  docker-down:
    cmds:
      - docker compose down -v

  openapi-validate:
    cmds:
      - test -f api/openapi.yaml
      - echo "OpenAPI file exists at api/openapi.yaml"

  obs-generate-traffic:
    cmds:
      - |
        bash -ec '
          for i in $(seq 1 40); do
            curl -s -o /dev/null "http://localhost:8080/api/v1/auth/google/login"
          done
          for i in $(seq 1 20); do
            curl -s -o /dev/null "http://localhost:8080/api/v1/auth/google/callback?state=bad&code=x"
          done
          for i in $(seq 1 20); do
            curl -s -o /dev/null -X POST "http://localhost:8080/api/v1/auth/refresh"
          done
        '

  obs-validate:
    cmds:
      - |
        bash -ec '
          : "${GRAFANA_USER:=admin}"
          : "${GRAFANA_PASSWORD:=admin}"
          task obs-generate-traffic
          sleep 10

          START=$(date -u -d "20 minutes ago" +%s)
          END=$(date -u +%s)
          curl -s -u "${GRAFANA_USER}:${GRAFANA_PASSWORD}" \
            "http://localhost:3000/api/datasources/proxy/1/api/v1/query_exemplars?query=auth_request_duration_seconds_bucket&start=${START}&end=${END}" \
            > /tmp/obs_exemplars.json

          EXEMPLAR_COUNT=$(jq ".data | length" /tmp/obs_exemplars.json)
          if [ "${EXEMPLAR_COUNT}" -eq 0 ]; then
            echo "No exemplars found for auth_request_duration_seconds_bucket"
            exit 1
          fi

          TRACE_ID=$(jq -r ".data[0].exemplars[0].labels.trace_id" /tmp/obs_exemplars.json)
          [ -n "${TRACE_ID}" ] && [ "${TRACE_ID}" != "null" ]

          curl -s -u "${GRAFANA_USER}:${GRAFANA_PASSWORD}" \
            "http://localhost:3000/api/datasources/proxy/3/api/traces/${TRACE_ID}" \
            > /tmp/obs_trace.json
          jq ".batches | length" /tmp/obs_trace.json | grep -E "^[1-9][0-9]*$" >/dev/null

          QUERY="{service_name=\"go-oauth-rbac-service\"} |= \"trace_id=${TRACE_ID}\""
          ENCODED_QUERY=$(printf "%s" "${QUERY}" | jq -sRr @uri)
          NOW_NS=$(date +%s%N)
          START_NS=$((NOW_NS - 30 * 60 * 1000000000))

          curl -s -u "${GRAFANA_USER}:${GRAFANA_PASSWORD}" \
            "http://localhost:3000/api/datasources/proxy/2/loki/api/v1/query_range?query=${ENCODED_QUERY}&start=${START_NS}&end=${NOW_NS}&limit=1&direction=backward" \
            > /tmp/obs_logs.json
          jq ".data.result | length" /tmp/obs_logs.json | grep -E "^[1-9][0-9]*$" >/dev/null

          echo "Observability validation passed"
          echo "Trace ID from exemplar: ${TRACE_ID}"
        '
