version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/api

  migrate:
    cmds:
      - go run ./cmd/api migrate

  wire:
    cmds:
      - go run -mod=mod github.com/google/wire/cmd/wire ./internal/di

  wire-check:
    cmds:
      - task wire
      - git diff --exit-code internal/di/wire_gen.go

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - go vet ./...

  ci:
    cmds:
      - task wire-check
      - task lint
      - task test

  docker-up:
    cmds:
      - docker compose up --build -d

  docker-down:
    cmds:
      - docker compose down -v

  openapi-validate:
    cmds:
      - test -f api/openapi.yaml
      - echo "OpenAPI file exists at api/openapi.yaml"
