version: '3'

includes:
  bazel:
    taskfile: ./taskfiles/bazel.yaml
    flatten: true
  go:
    taskfile: ./taskfiles/go.yaml
    flatten: true
  app:
    taskfile: ./taskfiles/app.yaml
    flatten: true
  obs:
    taskfile: ./taskfiles/obs.yaml
    flatten: true
  security:
    taskfile: ./taskfiles/security.yaml
    flatten: true
  ci:
    taskfile: ./taskfiles/ci.yaml
    flatten: true
