// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/oauth_repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/oauth_repository.go -destination internal/repository/gomock/mock_oauth_repository.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	reflect "reflect"

	domain "github.com/sandeepkv93/everything-backend-starter-kit/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthRepository is a mock of OAuthRepository interface.
type MockOAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockOAuthRepositoryMockRecorder is the mock recorder for MockOAuthRepository.
type MockOAuthRepositoryMockRecorder struct {
	mock *MockOAuthRepository
}

// NewMockOAuthRepository creates a new mock instance.
func NewMockOAuthRepository(ctrl *gomock.Controller) *MockOAuthRepository {
	mock := &MockOAuthRepository{ctrl: ctrl}
	mock.recorder = &MockOAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthRepository) EXPECT() *MockOAuthRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOAuthRepository) Create(account *domain.OAuthAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOAuthRepositoryMockRecorder) Create(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOAuthRepository)(nil).Create), account)
}

// FindByProvider mocks base method.
func (m *MockOAuthRepository) FindByProvider(provider, providerUserID string) (*domain.OAuthAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProvider", provider, providerUserID)
	ret0, _ := ret[0].(*domain.OAuthAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProvider indicates an expected call of FindByProvider.
func (mr *MockOAuthRepositoryMockRecorder) FindByProvider(provider, providerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProvider", reflect.TypeOf((*MockOAuthRepository)(nil).FindByProvider), provider, providerUserID)
}
