// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/feature_flag_repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/feature_flag_repository.go -destination internal/repository/gomock/mock_feature_flag_repository.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	reflect "reflect"

	domain "github.com/sandeepkv93/everything-backend-starter-kit/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFeatureFlagRepository is a mock of FeatureFlagRepository interface.
type MockFeatureFlagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureFlagRepositoryMockRecorder
	isgomock struct{}
}

// MockFeatureFlagRepositoryMockRecorder is the mock recorder for MockFeatureFlagRepository.
type MockFeatureFlagRepositoryMockRecorder struct {
	mock *MockFeatureFlagRepository
}

// NewMockFeatureFlagRepository creates a new mock instance.
func NewMockFeatureFlagRepository(ctrl *gomock.Controller) *MockFeatureFlagRepository {
	mock := &MockFeatureFlagRepository{ctrl: ctrl}
	mock.recorder = &MockFeatureFlagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureFlagRepository) EXPECT() *MockFeatureFlagRepositoryMockRecorder {
	return m.recorder
}

// CreateFlag mocks base method.
func (m *MockFeatureFlagRepository) CreateFlag(flag *domain.FeatureFlag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFlag", flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFlag indicates an expected call of CreateFlag.
func (mr *MockFeatureFlagRepositoryMockRecorder) CreateFlag(flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlag", reflect.TypeOf((*MockFeatureFlagRepository)(nil).CreateFlag), flag)
}

// CreateRule mocks base method.
func (m *MockFeatureFlagRepository) CreateRule(rule *domain.FeatureFlagRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockFeatureFlagRepositoryMockRecorder) CreateRule(rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockFeatureFlagRepository)(nil).CreateRule), rule)
}

// DeleteFlag mocks base method.
func (m *MockFeatureFlagRepository) DeleteFlag(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFlag", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFlag indicates an expected call of DeleteFlag.
func (mr *MockFeatureFlagRepositoryMockRecorder) DeleteFlag(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlag", reflect.TypeOf((*MockFeatureFlagRepository)(nil).DeleteFlag), id)
}

// DeleteRule mocks base method.
func (m *MockFeatureFlagRepository) DeleteRule(flagID, ruleID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", flagID, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockFeatureFlagRepositoryMockRecorder) DeleteRule(flagID, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockFeatureFlagRepository)(nil).DeleteRule), flagID, ruleID)
}

// FindFlagByID mocks base method.
func (m *MockFeatureFlagRepository) FindFlagByID(id uint) (*domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFlagByID", id)
	ret0, _ := ret[0].(*domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFlagByID indicates an expected call of FindFlagByID.
func (mr *MockFeatureFlagRepositoryMockRecorder) FindFlagByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFlagByID", reflect.TypeOf((*MockFeatureFlagRepository)(nil).FindFlagByID), id)
}

// FindFlagByKey mocks base method.
func (m *MockFeatureFlagRepository) FindFlagByKey(key string) (*domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFlagByKey", key)
	ret0, _ := ret[0].(*domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFlagByKey indicates an expected call of FindFlagByKey.
func (mr *MockFeatureFlagRepositoryMockRecorder) FindFlagByKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFlagByKey", reflect.TypeOf((*MockFeatureFlagRepository)(nil).FindFlagByKey), key)
}

// ListFlags mocks base method.
func (m *MockFeatureFlagRepository) ListFlags() ([]domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlags")
	ret0, _ := ret[0].([]domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFlags indicates an expected call of ListFlags.
func (mr *MockFeatureFlagRepositoryMockRecorder) ListFlags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlags", reflect.TypeOf((*MockFeatureFlagRepository)(nil).ListFlags))
}

// ListRules mocks base method.
func (m *MockFeatureFlagRepository) ListRules(flagID uint) ([]domain.FeatureFlagRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", flagID)
	ret0, _ := ret[0].([]domain.FeatureFlagRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockFeatureFlagRepositoryMockRecorder) ListRules(flagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockFeatureFlagRepository)(nil).ListRules), flagID)
}

// UpdateFlag mocks base method.
func (m *MockFeatureFlagRepository) UpdateFlag(flag *domain.FeatureFlag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFlag", flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFlag indicates an expected call of UpdateFlag.
func (mr *MockFeatureFlagRepositoryMockRecorder) UpdateFlag(flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFlag", reflect.TypeOf((*MockFeatureFlagRepository)(nil).UpdateFlag), flag)
}

// UpdateRule mocks base method.
func (m *MockFeatureFlagRepository) UpdateRule(rule *domain.FeatureFlagRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockFeatureFlagRepositoryMockRecorder) UpdateRule(rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockFeatureFlagRepository)(nil).UpdateRule), rule)
}
