// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/verification_token_repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/verification_token_repository.go -destination internal/repository/gomock/mock_verification_token_repository.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	reflect "reflect"
	time "time"

	domain "github.com/sandeepkv93/everything-backend-starter-kit/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationTokenRepository is a mock of VerificationTokenRepository interface.
type MockVerificationTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockVerificationTokenRepositoryMockRecorder is the mock recorder for MockVerificationTokenRepository.
type MockVerificationTokenRepositoryMockRecorder struct {
	mock *MockVerificationTokenRepository
}

// NewMockVerificationTokenRepository creates a new mock instance.
func NewMockVerificationTokenRepository(ctrl *gomock.Controller) *MockVerificationTokenRepository {
	mock := &MockVerificationTokenRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationTokenRepository) EXPECT() *MockVerificationTokenRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockVerificationTokenRepository) Consume(tokenID, userID uint, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", tokenID, userID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockVerificationTokenRepositoryMockRecorder) Consume(tokenID, userID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Consume), tokenID, userID, now)
}

// Create mocks base method.
func (m *MockVerificationTokenRepository) Create(token *domain.VerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVerificationTokenRepositoryMockRecorder) Create(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Create), token)
}

// FindActiveByHashPurpose mocks base method.
func (m *MockVerificationTokenRepository) FindActiveByHashPurpose(hash, purpose string, now time.Time) (*domain.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByHashPurpose", hash, purpose, now)
	ret0, _ := ret[0].(*domain.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByHashPurpose indicates an expected call of FindActiveByHashPurpose.
func (mr *MockVerificationTokenRepositoryMockRecorder) FindActiveByHashPurpose(hash, purpose, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByHashPurpose", reflect.TypeOf((*MockVerificationTokenRepository)(nil).FindActiveByHashPurpose), hash, purpose, now)
}

// InvalidateActiveByUserPurpose mocks base method.
func (m *MockVerificationTokenRepository) InvalidateActiveByUserPurpose(userID uint, purpose string, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateActiveByUserPurpose", userID, purpose, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateActiveByUserPurpose indicates an expected call of InvalidateActiveByUserPurpose.
func (mr *MockVerificationTokenRepositoryMockRecorder) InvalidateActiveByUserPurpose(userID, purpose, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateActiveByUserPurpose", reflect.TypeOf((*MockVerificationTokenRepository)(nil).InvalidateActiveByUserPurpose), userID, purpose, now)
}
