// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/local_credential_repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/local_credential_repository.go -destination internal/repository/gomock/mock_local_credential_repository.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	reflect "reflect"

	domain "github.com/sandeepkv93/everything-backend-starter-kit/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLocalCredentialRepository is a mock of LocalCredentialRepository interface.
type MockLocalCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLocalCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockLocalCredentialRepositoryMockRecorder is the mock recorder for MockLocalCredentialRepository.
type MockLocalCredentialRepositoryMockRecorder struct {
	mock *MockLocalCredentialRepository
}

// NewMockLocalCredentialRepository creates a new mock instance.
func NewMockLocalCredentialRepository(ctrl *gomock.Controller) *MockLocalCredentialRepository {
	mock := &MockLocalCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockLocalCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalCredentialRepository) EXPECT() *MockLocalCredentialRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLocalCredentialRepository) Create(credential *domain.LocalCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLocalCredentialRepositoryMockRecorder) Create(credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLocalCredentialRepository)(nil).Create), credential)
}

// FindByEmail mocks base method.
func (m *MockLocalCredentialRepository) FindByEmail(email string) (*domain.LocalCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(*domain.LocalCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockLocalCredentialRepositoryMockRecorder) FindByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockLocalCredentialRepository)(nil).FindByEmail), email)
}

// FindByUserID mocks base method.
func (m *MockLocalCredentialRepository) FindByUserID(userID uint) (*domain.LocalCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", userID)
	ret0, _ := ret[0].(*domain.LocalCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockLocalCredentialRepositoryMockRecorder) FindByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockLocalCredentialRepository)(nil).FindByUserID), userID)
}

// MarkEmailVerified mocks base method.
func (m *MockLocalCredentialRepository) MarkEmailVerified(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailVerified", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailVerified indicates an expected call of MarkEmailVerified.
func (mr *MockLocalCredentialRepositoryMockRecorder) MarkEmailVerified(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailVerified", reflect.TypeOf((*MockLocalCredentialRepository)(nil).MarkEmailVerified), userID)
}

// UpdatePassword mocks base method.
func (m *MockLocalCredentialRepository) UpdatePassword(userID uint, newHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", userID, newHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockLocalCredentialRepositoryMockRecorder) UpdatePassword(userID, newHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockLocalCredentialRepository)(nil).UpdatePassword), userID, newHash)
}
