// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/permission_repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/permission_repository.go -destination internal/repository/gomock/mock_permission_repository.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	reflect "reflect"

	domain "github.com/sandeepkv93/everything-backend-starter-kit/internal/domain"
	repository "github.com/sandeepkv93/everything-backend-starter-kit/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionRepository is a mock of PermissionRepository interface.
type MockPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockPermissionRepositoryMockRecorder is the mock recorder for MockPermissionRepository.
type MockPermissionRepositoryMockRecorder struct {
	mock *MockPermissionRepository
}

// NewMockPermissionRepository creates a new mock instance.
func NewMockPermissionRepository(ctrl *gomock.Controller) *MockPermissionRepository {
	mock := &MockPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepository) EXPECT() *MockPermissionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissionRepository) Create(permission *domain.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPermissionRepositoryMockRecorder) Create(permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionRepository)(nil).Create), permission)
}

// DeleteByID mocks base method.
func (m *MockPermissionRepository) DeleteByID(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockPermissionRepositoryMockRecorder) DeleteByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockPermissionRepository)(nil).DeleteByID), id)
}

// FindByID mocks base method.
func (m *MockPermissionRepository) FindByID(id uint) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPermissionRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPermissionRepository)(nil).FindByID), id)
}

// FindByPairs mocks base method.
func (m *MockPermissionRepository) FindByPairs(pairs [][2]string) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPairs", pairs)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPairs indicates an expected call of FindByPairs.
func (mr *MockPermissionRepositoryMockRecorder) FindByPairs(pairs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPairs", reflect.TypeOf((*MockPermissionRepository)(nil).FindByPairs), pairs)
}

// FindByResourceAction mocks base method.
func (m *MockPermissionRepository) FindByResourceAction(resource, action string) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByResourceAction", resource, action)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByResourceAction indicates an expected call of FindByResourceAction.
func (mr *MockPermissionRepositoryMockRecorder) FindByResourceAction(resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByResourceAction", reflect.TypeOf((*MockPermissionRepository)(nil).FindByResourceAction), resource, action)
}

// List mocks base method.
func (m *MockPermissionRepository) List() ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPermissionRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermissionRepository)(nil).List))
}

// ListPaged mocks base method.
func (m *MockPermissionRepository) ListPaged(req repository.PageRequest, sortBy, sortOrder, resource, action string) (repository.PageResult[domain.Permission], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaged", req, sortBy, sortOrder, resource, action)
	ret0, _ := ret[0].(repository.PageResult[domain.Permission])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaged indicates an expected call of ListPaged.
func (mr *MockPermissionRepositoryMockRecorder) ListPaged(req, sortBy, sortOrder, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaged", reflect.TypeOf((*MockPermissionRepository)(nil).ListPaged), req, sortBy, sortOrder, resource, action)
}

// Update mocks base method.
func (m *MockPermissionRepository) Update(permission *domain.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPermissionRepositoryMockRecorder) Update(permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPermissionRepository)(nil).Update), permission)
}
