// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/session_repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/session_repository.go -destination internal/repository/gomock/mock_session_repository.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	reflect "reflect"

	domain "github.com/sandeepkv93/everything-backend-starter-kit/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// CleanupExpired mocks base method.
func (m *MockSessionRepository) CleanupExpired() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpired")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpired indicates an expected call of CleanupExpired.
func (mr *MockSessionRepositoryMockRecorder) CleanupExpired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpired", reflect.TypeOf((*MockSessionRepository)(nil).CleanupExpired))
}

// Create mocks base method.
func (m *MockSessionRepository) Create(s *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), s)
}

// FindActiveByTokenIDForUser mocks base method.
func (m *MockSessionRepository) FindActiveByTokenIDForUser(userID uint, tokenID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByTokenIDForUser", userID, tokenID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByTokenIDForUser indicates an expected call of FindActiveByTokenIDForUser.
func (mr *MockSessionRepositoryMockRecorder) FindActiveByTokenIDForUser(userID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByTokenIDForUser", reflect.TypeOf((*MockSessionRepository)(nil).FindActiveByTokenIDForUser), userID, tokenID)
}

// FindByHash mocks base method.
func (m *MockSessionRepository) FindByHash(hash string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", hash)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockSessionRepositoryMockRecorder) FindByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockSessionRepository)(nil).FindByHash), hash)
}

// FindByIDForUser mocks base method.
func (m *MockSessionRepository) FindByIDForUser(userID, sessionID uint) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDForUser", userID, sessionID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDForUser indicates an expected call of FindByIDForUser.
func (mr *MockSessionRepositoryMockRecorder) FindByIDForUser(userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDForUser", reflect.TypeOf((*MockSessionRepository)(nil).FindByIDForUser), userID, sessionID)
}

// ListActiveByUserID mocks base method.
func (m *MockSessionRepository) ListActiveByUserID(userID uint) ([]domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByUserID", userID)
	ret0, _ := ret[0].([]domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByUserID indicates an expected call of ListActiveByUserID.
func (mr *MockSessionRepositoryMockRecorder) ListActiveByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByUserID", reflect.TypeOf((*MockSessionRepository)(nil).ListActiveByUserID), userID)
}

// MarkReuseDetectedByHash mocks base method.
func (m *MockSessionRepository) MarkReuseDetectedByHash(hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkReuseDetectedByHash", hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkReuseDetectedByHash indicates an expected call of MarkReuseDetectedByHash.
func (mr *MockSessionRepositoryMockRecorder) MarkReuseDetectedByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReuseDetectedByHash", reflect.TypeOf((*MockSessionRepository)(nil).MarkReuseDetectedByHash), hash)
}

// RevokeByFamilyID mocks base method.
func (m *MockSessionRepository) RevokeByFamilyID(familyID, reason string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByFamilyID", familyID, reason)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeByFamilyID indicates an expected call of RevokeByFamilyID.
func (mr *MockSessionRepositoryMockRecorder) RevokeByFamilyID(familyID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByFamilyID", reflect.TypeOf((*MockSessionRepository)(nil).RevokeByFamilyID), familyID, reason)
}

// RevokeByHash mocks base method.
func (m *MockSessionRepository) RevokeByHash(hash, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByHash", hash, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByHash indicates an expected call of RevokeByHash.
func (mr *MockSessionRepositoryMockRecorder) RevokeByHash(hash, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByHash", reflect.TypeOf((*MockSessionRepository)(nil).RevokeByHash), hash, reason)
}

// RevokeByIDForUser mocks base method.
func (m *MockSessionRepository) RevokeByIDForUser(userID, sessionID uint, reason string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByIDForUser", userID, sessionID, reason)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeByIDForUser indicates an expected call of RevokeByIDForUser.
func (mr *MockSessionRepositoryMockRecorder) RevokeByIDForUser(userID, sessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByIDForUser", reflect.TypeOf((*MockSessionRepository)(nil).RevokeByIDForUser), userID, sessionID, reason)
}

// RevokeByUserID mocks base method.
func (m *MockSessionRepository) RevokeByUserID(userID uint, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByUserID", userID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByUserID indicates an expected call of RevokeByUserID.
func (mr *MockSessionRepositoryMockRecorder) RevokeByUserID(userID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByUserID", reflect.TypeOf((*MockSessionRepository)(nil).RevokeByUserID), userID, reason)
}

// RevokeOthersByUser mocks base method.
func (m *MockSessionRepository) RevokeOthersByUser(userID, keepSessionID uint, reason string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeOthersByUser", userID, keepSessionID, reason)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeOthersByUser indicates an expected call of RevokeOthersByUser.
func (mr *MockSessionRepositoryMockRecorder) RevokeOthersByUser(userID, keepSessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeOthersByUser", reflect.TypeOf((*MockSessionRepository)(nil).RevokeOthersByUser), userID, keepSessionID, reason)
}

// RotateSession mocks base method.
func (m *MockSessionRepository) RotateSession(oldHash string, newSession *domain.Session) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateSession", oldHash, newSession)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateSession indicates an expected call of RotateSession.
func (mr *MockSessionRepositoryMockRecorder) RotateSession(oldHash, newSession any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateSession", reflect.TypeOf((*MockSessionRepository)(nil).RotateSession), oldHash, newSession)
}

// UpdateTokenLineageByHash mocks base method.
func (m *MockSessionRepository) UpdateTokenLineageByHash(hash, tokenID, familyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenLineageByHash", hash, tokenID, familyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenLineageByHash indicates an expected call of UpdateTokenLineageByHash.
func (mr *MockSessionRepositoryMockRecorder) UpdateTokenLineageByHash(hash, tokenID, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenLineageByHash", reflect.TypeOf((*MockSessionRepository)(nil).UpdateTokenLineageByHash), hash, tokenID, familyID)
}
