// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/middleware/rate_limit_middleware.go
//
// Generated by this command:
//
//	mockgen -source internal/http/middleware/rate_limit_middleware.go -destination internal/http/middleware/gomock/mock_rate_limit_middleware.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	context "context"
	reflect "reflect"

	middleware "github.com/sandeepkv93/everything-backend-starter-kit/internal/http/middleware"
	gomock "go.uber.org/mock/gomock"
)

// MockLimiter is a mock of Limiter interface.
type MockLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockLimiterMockRecorder
	isgomock struct{}
}

// MockLimiterMockRecorder is the mock recorder for MockLimiter.
type MockLimiterMockRecorder struct {
	mock *MockLimiter
}

// NewMockLimiter creates a new mock instance.
func NewMockLimiter(ctrl *gomock.Controller) *MockLimiter {
	mock := &MockLimiter{ctrl: ctrl}
	mock.recorder = &MockLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimiter) EXPECT() *MockLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockLimiter) Allow(ctx context.Context, key string, policy middleware.RateLimitPolicy) (middleware.Decision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, key, policy)
	ret0, _ := ret[0].(middleware.Decision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockLimiterMockRecorder) Allow(ctx, key, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockLimiter)(nil).Allow), ctx, key, policy)
}
