// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/app"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/config"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/http/handler"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/http/router"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/repository"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/service"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	runtime, err := provideObservabilityRuntime(configConfig)
	if err != nil {
		return nil, err
	}
	logger := provideAppLogger(configConfig, runtime)
	googleOAuthProvider := service.NewGoogleOAuthProvider(configConfig)
	db, err := provideRuntimeDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	oAuthRepository := repository.NewOAuthRepository(db)
	roleRepository := repository.NewRoleRepository(db)
	oAuthService := service.NewOAuthService(googleOAuthProvider, userRepository, oAuthRepository, roleRepository)
	jwtManager := provideJWTManager(configConfig)
	sessionRepository := repository.NewSessionRepository(db)
	tokenService := provideTokenService(configConfig, jwtManager, sessionRepository)
	rbacService := service.NewRBACService()
	userService := service.NewUserService(userRepository, rbacService)
	localCredentialRepository := repository.NewLocalCredentialRepository(db)
	verificationTokenRepository := repository.NewVerificationTokenRepository(db)
	devEmailVerificationNotifier := service.NewDevEmailVerificationNotifier(logger)
	authService := service.NewAuthService(configConfig, oAuthService, tokenService, userService, roleRepository, localCredentialRepository, verificationTokenRepository, devEmailVerificationNotifier, devEmailVerificationNotifier)
	universalClient := provideRedisClient(configConfig)
	authAbuseGuard := provideAuthAbuseGuard(configConfig, universalClient)
	cookieManager := provideCookieManager(configConfig)
	authHandler := provideAuthHandler(authService, authAbuseGuard, cookieManager, configConfig)
	sessionService := provideSessionService(configConfig, sessionRepository)
	userHandler := handler.NewUserHandler(userService, sessionService)
	permissionRepository := repository.NewPermissionRepository(db)
	rbacPermissionCacheStore := provideRBACPermissionCacheStore(configConfig, universalClient)
	permissionResolver := providePermissionResolver(configConfig, userService, rbacPermissionCacheStore)
	adminListCacheStore := provideAdminListCacheStore(configConfig, universalClient)
	negativeLookupCacheStore := provideNegativeLookupCacheStore(configConfig, universalClient)
	adminHandler := handler.NewAdminHandler(userService, userRepository, roleRepository, permissionRepository, rbacService, permissionResolver, adminListCacheStore, negativeLookupCacheStore, db, configConfig)
	globalRateLimiterFunc := provideGlobalRateLimiter(configConfig, universalClient, jwtManager)
	authRateLimiterFunc := provideAuthRateLimiter(configConfig, universalClient)
	forgotRateLimiterFunc := provideForgotRateLimiter(configConfig, universalClient)
	routeRateLimitPolicies := provideRouteRateLimitPolicies(configConfig, universalClient, jwtManager)
	idempotencyStore := provideIdempotencyStore(configConfig, db, universalClient)
	idempotencyMiddlewareFactory := provideIdempotencyMiddlewareFactory(configConfig, idempotencyStore)
	probeRunner := provideReadinessProbeRunner(configConfig, db, universalClient)
	dependencies := provideRouterDependencies(authHandler, userHandler, adminHandler, jwtManager, rbacService, permissionResolver, globalRateLimiterFunc, authRateLimiterFunc, forgotRateLimiterFunc, routeRateLimitPolicies, idempotencyMiddlewareFactory, probeRunner, configConfig)
	httpHandler := router.NewRouter(dependencies)
	server := provideHTTPServer(configConfig, httpHandler)
	appApp := provideApp(configConfig, logger, server, runtime, db, universalClient, probeRunner)
	return appApp, nil
}

func InitializeMigrationRunner() (*MigrationRunner, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := provideOpenDB(configConfig)
	if err != nil {
		return nil, err
	}
	migrationRunner := NewMigrationRunner(configConfig, db)
	return migrationRunner, nil
}
