// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/app"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/config"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/http/handler"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/http/router"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/repository"
	"github.com/sandeepkv93/secure-observable-go-backend-starter-kit/internal/service"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	runtime, err := provideObservabilityRuntime(configConfig)
	if err != nil {
		return nil, err
	}
	logger := provideAppLogger(configConfig, runtime)
	googleOAuthProvider := service.NewGoogleOAuthProvider(configConfig)
	db, err := provideRuntimeDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	oAuthRepository := repository.NewOAuthRepository(db)
	roleRepository := repository.NewRoleRepository(db)
	oAuthService := service.NewOAuthService(googleOAuthProvider, userRepository, oAuthRepository, roleRepository)
	jwtManager := provideJWTManager(configConfig)
	sessionRepository := repository.NewSessionRepository(db)
	tokenService := provideTokenService(configConfig, jwtManager, sessionRepository)
	rbacService := service.NewRBACService()
	userService := service.NewUserService(userRepository, rbacService)
	localCredentialRepository := repository.NewLocalCredentialRepository(db)
	authService := service.NewAuthService(configConfig, oAuthService, tokenService, userService, roleRepository, localCredentialRepository)
	cookieManager := provideCookieManager(configConfig)
	authHandler := provideAuthHandler(authService, cookieManager, configConfig)
	userHandler := handler.NewUserHandler(userService)
	permissionRepository := repository.NewPermissionRepository(db)
	adminHandler := handler.NewAdminHandler(userService, roleRepository, permissionRepository)
	universalClient := provideRedisClient(configConfig)
	globalRateLimiterFunc := provideGlobalRateLimiter(configConfig, universalClient)
	authRateLimiterFunc := provideAuthRateLimiter(configConfig, universalClient)
	probeRunner := provideReadinessProbeRunner(configConfig, db, universalClient)
	dependencies := provideRouterDependencies(authHandler, userHandler, adminHandler, jwtManager, rbacService, globalRateLimiterFunc, authRateLimiterFunc, probeRunner, configConfig)
	httpHandler := router.NewRouter(dependencies)
	server := provideHTTPServer(configConfig, httpHandler)
	appApp := provideApp(configConfig, logger, server, runtime, db, universalClient, probeRunner)
	return appApp, nil
}

func InitializeMigrationRunner() (*MigrationRunner, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := provideOpenDB(configConfig)
	if err != nil {
		return nil, err
	}
	migrationRunner := NewMigrationRunner(configConfig, db)
	return migrationRunner, nil
}
