version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/api

  migrate:
    cmds:
      - go run ./cmd/migrate up

  migrate:status:
    cmds:
      - go run ./cmd/migrate status

  migrate:plan:
    cmds:
      - go run ./cmd/migrate plan

  seed:
    cmds:
      - go run ./cmd/seed apply

  seed:dry-run:
    cmds:
      - go run ./cmd/seed dry-run

  seed:verify-local-email:
    cmds:
      - go run ./cmd/seed verify-local-email

  hooks-install:
    cmds:
      - git config core.hooksPath .githooks
      - chmod +x .githooks/pre-commit .githooks/pre-push

  docker-up:
    cmds:
      - docker compose up --build -d

  docker-down:
    cmds:
      - docker compose down -v

  openapi-validate:
    cmds:
      - test -f api/openapi.yaml
      - echo "OpenAPI file exists at api/openapi.yaml"
