// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source internal/service/interfaces.go -destination internal/service/mock_interfaces_test.go -package service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	http "net/http"
	reflect "reflect"

	domain "github.com/sandeepkv93/everything-backend-starter-kit/internal/domain"
	repository "github.com/sandeepkv93/everything-backend-starter-kit/internal/repository"
	security "github.com/sandeepkv93/everything-backend-starter-kit/internal/security"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// ChangeLocalPassword mocks base method.
func (m *MockAuthServiceInterface) ChangeLocalPassword(userID uint, currentPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeLocalPassword", userID, currentPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeLocalPassword indicates an expected call of ChangeLocalPassword.
func (mr *MockAuthServiceInterfaceMockRecorder) ChangeLocalPassword(userID, currentPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeLocalPassword", reflect.TypeOf((*MockAuthServiceInterface)(nil).ChangeLocalPassword), userID, currentPassword, newPassword)
}

// ConfirmLocalEmailVerification mocks base method.
func (m *MockAuthServiceInterface) ConfirmLocalEmailVerification(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmLocalEmailVerification", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmLocalEmailVerification indicates an expected call of ConfirmLocalEmailVerification.
func (mr *MockAuthServiceInterfaceMockRecorder) ConfirmLocalEmailVerification(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmLocalEmailVerification", reflect.TypeOf((*MockAuthServiceInterface)(nil).ConfirmLocalEmailVerification), token)
}

// ForgotLocalPassword mocks base method.
func (m *MockAuthServiceInterface) ForgotLocalPassword(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotLocalPassword", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForgotLocalPassword indicates an expected call of ForgotLocalPassword.
func (mr *MockAuthServiceInterfaceMockRecorder) ForgotLocalPassword(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotLocalPassword", reflect.TypeOf((*MockAuthServiceInterface)(nil).ForgotLocalPassword), email)
}

// GoogleLoginURL mocks base method.
func (m *MockAuthServiceInterface) GoogleLoginURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoogleLoginURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// GoogleLoginURL indicates an expected call of GoogleLoginURL.
func (mr *MockAuthServiceInterfaceMockRecorder) GoogleLoginURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoogleLoginURL", reflect.TypeOf((*MockAuthServiceInterface)(nil).GoogleLoginURL), state)
}

// LoginWithGoogleCode mocks base method.
func (m *MockAuthServiceInterface) LoginWithGoogleCode(code, ua, ip string) (*LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithGoogleCode", code, ua, ip)
	ret0, _ := ret[0].(*LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginWithGoogleCode indicates an expected call of LoginWithGoogleCode.
func (mr *MockAuthServiceInterfaceMockRecorder) LoginWithGoogleCode(code, ua, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithGoogleCode", reflect.TypeOf((*MockAuthServiceInterface)(nil).LoginWithGoogleCode), code, ua, ip)
}

// LoginWithLocalPassword mocks base method.
func (m *MockAuthServiceInterface) LoginWithLocalPassword(email, password, ua, ip string) (*LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithLocalPassword", email, password, ua, ip)
	ret0, _ := ret[0].(*LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginWithLocalPassword indicates an expected call of LoginWithLocalPassword.
func (mr *MockAuthServiceInterfaceMockRecorder) LoginWithLocalPassword(email, password, ua, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithLocalPassword", reflect.TypeOf((*MockAuthServiceInterface)(nil).LoginWithLocalPassword), email, password, ua, ip)
}

// Logout mocks base method.
func (m *MockAuthServiceInterface) Logout(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceInterfaceMockRecorder) Logout(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceInterface)(nil).Logout), userID)
}

// ParseUserID mocks base method.
func (m *MockAuthServiceInterface) ParseUserID(subject string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseUserID", subject)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseUserID indicates an expected call of ParseUserID.
func (mr *MockAuthServiceInterfaceMockRecorder) ParseUserID(subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseUserID", reflect.TypeOf((*MockAuthServiceInterface)(nil).ParseUserID), subject)
}

// Refresh mocks base method.
func (m *MockAuthServiceInterface) Refresh(refreshToken, ua, ip string) (*LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", refreshToken, ua, ip)
	ret0, _ := ret[0].(*LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthServiceInterfaceMockRecorder) Refresh(refreshToken, ua, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthServiceInterface)(nil).Refresh), refreshToken, ua, ip)
}

// RegisterLocal mocks base method.
func (m *MockAuthServiceInterface) RegisterLocal(email, name, password, ua, ip string) (*LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterLocal", email, name, password, ua, ip)
	ret0, _ := ret[0].(*LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterLocal indicates an expected call of RegisterLocal.
func (mr *MockAuthServiceInterfaceMockRecorder) RegisterLocal(email, name, password, ua, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterLocal", reflect.TypeOf((*MockAuthServiceInterface)(nil).RegisterLocal), email, name, password, ua, ip)
}

// RequestLocalEmailVerification mocks base method.
func (m *MockAuthServiceInterface) RequestLocalEmailVerification(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestLocalEmailVerification", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestLocalEmailVerification indicates an expected call of RequestLocalEmailVerification.
func (mr *MockAuthServiceInterfaceMockRecorder) RequestLocalEmailVerification(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestLocalEmailVerification", reflect.TypeOf((*MockAuthServiceInterface)(nil).RequestLocalEmailVerification), email)
}

// ResetLocalPassword mocks base method.
func (m *MockAuthServiceInterface) ResetLocalPassword(token, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetLocalPassword", token, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetLocalPassword indicates an expected call of ResetLocalPassword.
func (mr *MockAuthServiceInterfaceMockRecorder) ResetLocalPassword(token, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetLocalPassword", reflect.TypeOf((*MockAuthServiceInterface)(nil).ResetLocalPassword), token, newPassword)
}

// MockUserServiceInterface is a mock of UserServiceInterface interface.
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface.
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance.
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserServiceInterface) GetByID(id uint) (*domain.User, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserServiceInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserServiceInterface)(nil).GetByID), id)
}

// List mocks base method.
func (m *MockUserServiceInterface) List() ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserServiceInterfaceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserServiceInterface)(nil).List))
}

// SetRoles mocks base method.
func (m *MockUserServiceInterface) SetRoles(userID uint, roleIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoles", userID, roleIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRoles indicates an expected call of SetRoles.
func (mr *MockUserServiceInterfaceMockRecorder) SetRoles(userID, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoles", reflect.TypeOf((*MockUserServiceInterface)(nil).SetRoles), userID, roleIDs)
}

// MockRBACAuthorizer is a mock of RBACAuthorizer interface.
type MockRBACAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockRBACAuthorizerMockRecorder
	isgomock struct{}
}

// MockRBACAuthorizerMockRecorder is the mock recorder for MockRBACAuthorizer.
type MockRBACAuthorizerMockRecorder struct {
	mock *MockRBACAuthorizer
}

// NewMockRBACAuthorizer creates a new mock instance.
func NewMockRBACAuthorizer(ctrl *gomock.Controller) *MockRBACAuthorizer {
	mock := &MockRBACAuthorizer{ctrl: ctrl}
	mock.recorder = &MockRBACAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBACAuthorizer) EXPECT() *MockRBACAuthorizerMockRecorder {
	return m.recorder
}

// HasPermission mocks base method.
func (m *MockRBACAuthorizer) HasPermission(permissions []string, required string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermission", permissions, required)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPermission indicates an expected call of HasPermission.
func (mr *MockRBACAuthorizerMockRecorder) HasPermission(permissions, required any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermission", reflect.TypeOf((*MockRBACAuthorizer)(nil).HasPermission), permissions, required)
}

// MockPermissionResolver is a mock of PermissionResolver interface.
type MockPermissionResolver struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionResolverMockRecorder
	isgomock struct{}
}

// MockPermissionResolverMockRecorder is the mock recorder for MockPermissionResolver.
type MockPermissionResolverMockRecorder struct {
	mock *MockPermissionResolver
}

// NewMockPermissionResolver creates a new mock instance.
func NewMockPermissionResolver(ctrl *gomock.Controller) *MockPermissionResolver {
	mock := &MockPermissionResolver{ctrl: ctrl}
	mock.recorder = &MockPermissionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionResolver) EXPECT() *MockPermissionResolverMockRecorder {
	return m.recorder
}

// InvalidateAll mocks base method.
func (m *MockPermissionResolver) InvalidateAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAll indicates an expected call of InvalidateAll.
func (mr *MockPermissionResolverMockRecorder) InvalidateAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAll", reflect.TypeOf((*MockPermissionResolver)(nil).InvalidateAll), ctx)
}

// InvalidateUser mocks base method.
func (m *MockPermissionResolver) InvalidateUser(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUser indicates an expected call of InvalidateUser.
func (mr *MockPermissionResolverMockRecorder) InvalidateUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUser", reflect.TypeOf((*MockPermissionResolver)(nil).InvalidateUser), ctx, userID)
}

// ResolvePermissions mocks base method.
func (m *MockPermissionResolver) ResolvePermissions(ctx context.Context, claims *security.Claims) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePermissions", ctx, claims)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePermissions indicates an expected call of ResolvePermissions.
func (mr *MockPermissionResolverMockRecorder) ResolvePermissions(ctx, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePermissions", reflect.TypeOf((*MockPermissionResolver)(nil).ResolvePermissions), ctx, claims)
}

// MockSessionServiceInterface is a mock of SessionServiceInterface interface.
type MockSessionServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockSessionServiceInterfaceMockRecorder is the mock recorder for MockSessionServiceInterface.
type MockSessionServiceInterfaceMockRecorder struct {
	mock *MockSessionServiceInterface
}

// NewMockSessionServiceInterface creates a new mock instance.
func NewMockSessionServiceInterface(ctrl *gomock.Controller) *MockSessionServiceInterface {
	mock := &MockSessionServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSessionServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionServiceInterface) EXPECT() *MockSessionServiceInterfaceMockRecorder {
	return m.recorder
}

// ListActiveSessions mocks base method.
func (m *MockSessionServiceInterface) ListActiveSessions(userID, currentSessionID uint) ([]SessionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveSessions", userID, currentSessionID)
	ret0, _ := ret[0].([]SessionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveSessions indicates an expected call of ListActiveSessions.
func (mr *MockSessionServiceInterfaceMockRecorder) ListActiveSessions(userID, currentSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveSessions", reflect.TypeOf((*MockSessionServiceInterface)(nil).ListActiveSessions), userID, currentSessionID)
}

// ResolveCurrentSessionID mocks base method.
func (m *MockSessionServiceInterface) ResolveCurrentSessionID(r *http.Request, claims *security.Claims, userID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCurrentSessionID", r, claims, userID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCurrentSessionID indicates an expected call of ResolveCurrentSessionID.
func (mr *MockSessionServiceInterfaceMockRecorder) ResolveCurrentSessionID(r, claims, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCurrentSessionID", reflect.TypeOf((*MockSessionServiceInterface)(nil).ResolveCurrentSessionID), r, claims, userID)
}

// RevokeOtherSessions mocks base method.
func (m *MockSessionServiceInterface) RevokeOtherSessions(userID, currentSessionID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeOtherSessions", userID, currentSessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeOtherSessions indicates an expected call of RevokeOtherSessions.
func (mr *MockSessionServiceInterfaceMockRecorder) RevokeOtherSessions(userID, currentSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeOtherSessions", reflect.TypeOf((*MockSessionServiceInterface)(nil).RevokeOtherSessions), userID, currentSessionID)
}

// RevokeSession mocks base method.
func (m *MockSessionServiceInterface) RevokeSession(userID, sessionID uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", userID, sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockSessionServiceInterfaceMockRecorder) RevokeSession(userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockSessionServiceInterface)(nil).RevokeSession), userID, sessionID)
}

// MockFeatureFlagService is a mock of FeatureFlagService interface.
type MockFeatureFlagService struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureFlagServiceMockRecorder
	isgomock struct{}
}

// MockFeatureFlagServiceMockRecorder is the mock recorder for MockFeatureFlagService.
type MockFeatureFlagServiceMockRecorder struct {
	mock *MockFeatureFlagService
}

// NewMockFeatureFlagService creates a new mock instance.
func NewMockFeatureFlagService(ctrl *gomock.Controller) *MockFeatureFlagService {
	mock := &MockFeatureFlagService{ctrl: ctrl}
	mock.recorder = &MockFeatureFlagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureFlagService) EXPECT() *MockFeatureFlagServiceMockRecorder {
	return m.recorder
}

// CreateFlag mocks base method.
func (m *MockFeatureFlagService) CreateFlag(ctx context.Context, flag *domain.FeatureFlag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFlag", ctx, flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFlag indicates an expected call of CreateFlag.
func (mr *MockFeatureFlagServiceMockRecorder) CreateFlag(ctx, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlag", reflect.TypeOf((*MockFeatureFlagService)(nil).CreateFlag), ctx, flag)
}

// CreateRule mocks base method.
func (m *MockFeatureFlagService) CreateRule(ctx context.Context, rule *domain.FeatureFlagRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockFeatureFlagServiceMockRecorder) CreateRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockFeatureFlagService)(nil).CreateRule), ctx, rule)
}

// DeleteFlag mocks base method.
func (m *MockFeatureFlagService) DeleteFlag(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFlag", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFlag indicates an expected call of DeleteFlag.
func (mr *MockFeatureFlagServiceMockRecorder) DeleteFlag(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlag", reflect.TypeOf((*MockFeatureFlagService)(nil).DeleteFlag), ctx, id)
}

// DeleteRule mocks base method.
func (m *MockFeatureFlagService) DeleteRule(ctx context.Context, flagID, ruleID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, flagID, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockFeatureFlagServiceMockRecorder) DeleteRule(ctx, flagID, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockFeatureFlagService)(nil).DeleteRule), ctx, flagID, ruleID)
}

// EvaluateAll mocks base method.
func (m *MockFeatureFlagService) EvaluateAll(ctx context.Context, evalCtx FeatureFlagEvaluationContext) ([]FeatureFlagEvaluationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateAll", ctx, evalCtx)
	ret0, _ := ret[0].([]FeatureFlagEvaluationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateAll indicates an expected call of EvaluateAll.
func (mr *MockFeatureFlagServiceMockRecorder) EvaluateAll(ctx, evalCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateAll", reflect.TypeOf((*MockFeatureFlagService)(nil).EvaluateAll), ctx, evalCtx)
}

// EvaluateByKey mocks base method.
func (m *MockFeatureFlagService) EvaluateByKey(ctx context.Context, key string, evalCtx FeatureFlagEvaluationContext) (*FeatureFlagEvaluationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateByKey", ctx, key, evalCtx)
	ret0, _ := ret[0].(*FeatureFlagEvaluationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateByKey indicates an expected call of EvaluateByKey.
func (mr *MockFeatureFlagServiceMockRecorder) EvaluateByKey(ctx, key, evalCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateByKey", reflect.TypeOf((*MockFeatureFlagService)(nil).EvaluateByKey), ctx, key, evalCtx)
}

// GetFlagByID mocks base method.
func (m *MockFeatureFlagService) GetFlagByID(ctx context.Context, id uint) (*domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlagByID", ctx, id)
	ret0, _ := ret[0].(*domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlagByID indicates an expected call of GetFlagByID.
func (mr *MockFeatureFlagServiceMockRecorder) GetFlagByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlagByID", reflect.TypeOf((*MockFeatureFlagService)(nil).GetFlagByID), ctx, id)
}

// ListFlags mocks base method.
func (m *MockFeatureFlagService) ListFlags(ctx context.Context) ([]domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlags", ctx)
	ret0, _ := ret[0].([]domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFlags indicates an expected call of ListFlags.
func (mr *MockFeatureFlagServiceMockRecorder) ListFlags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlags", reflect.TypeOf((*MockFeatureFlagService)(nil).ListFlags), ctx)
}

// ListRules mocks base method.
func (m *MockFeatureFlagService) ListRules(ctx context.Context, flagID uint) ([]domain.FeatureFlagRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx, flagID)
	ret0, _ := ret[0].([]domain.FeatureFlagRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockFeatureFlagServiceMockRecorder) ListRules(ctx, flagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockFeatureFlagService)(nil).ListRules), ctx, flagID)
}

// UpdateFlag mocks base method.
func (m *MockFeatureFlagService) UpdateFlag(ctx context.Context, flag *domain.FeatureFlag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFlag", ctx, flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFlag indicates an expected call of UpdateFlag.
func (mr *MockFeatureFlagServiceMockRecorder) UpdateFlag(ctx, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFlag", reflect.TypeOf((*MockFeatureFlagService)(nil).UpdateFlag), ctx, flag)
}

// UpdateRule mocks base method.
func (m *MockFeatureFlagService) UpdateRule(ctx context.Context, rule *domain.FeatureFlagRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockFeatureFlagServiceMockRecorder) UpdateRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockFeatureFlagService)(nil).UpdateRule), ctx, rule)
}

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
	isgomock struct{}
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductService) Create(ctx context.Context, input CreateProductInput) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProductServiceMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductService)(nil).Create), ctx, input)
}

// DeleteByID mocks base method.
func (m *MockProductService) DeleteByID(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockProductServiceMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockProductService)(nil).DeleteByID), ctx, id)
}

// GetByID mocks base method.
func (m *MockProductService) GetByID(ctx context.Context, id uint) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProductServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProductService)(nil).GetByID), ctx, id)
}

// ListPaged mocks base method.
func (m *MockProductService) ListPaged(ctx context.Context, req repository.PageRequest) (repository.PageResult[domain.Product], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaged", ctx, req)
	ret0, _ := ret[0].(repository.PageResult[domain.Product])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaged indicates an expected call of ListPaged.
func (mr *MockProductServiceMockRecorder) ListPaged(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaged", reflect.TypeOf((*MockProductService)(nil).ListPaged), ctx, req)
}

// Update mocks base method.
func (m *MockProductService) Update(ctx context.Context, id uint, input UpdateProductInput) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProductServiceMockRecorder) Update(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductService)(nil).Update), ctx, id, input)
}
