// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/feature_flag_cache_store.go
//
// Generated by this command:
//
//	mockgen -source internal/service/feature_flag_cache_store.go -destination internal/service/gomock/mock_feature_flag_cache_store.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockFeatureFlagEvaluationCacheStore is a mock of FeatureFlagEvaluationCacheStore interface.
type MockFeatureFlagEvaluationCacheStore struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureFlagEvaluationCacheStoreMockRecorder
	isgomock struct{}
}

// MockFeatureFlagEvaluationCacheStoreMockRecorder is the mock recorder for MockFeatureFlagEvaluationCacheStore.
type MockFeatureFlagEvaluationCacheStoreMockRecorder struct {
	mock *MockFeatureFlagEvaluationCacheStore
}

// NewMockFeatureFlagEvaluationCacheStore creates a new mock instance.
func NewMockFeatureFlagEvaluationCacheStore(ctrl *gomock.Controller) *MockFeatureFlagEvaluationCacheStore {
	mock := &MockFeatureFlagEvaluationCacheStore{ctrl: ctrl}
	mock.recorder = &MockFeatureFlagEvaluationCacheStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureFlagEvaluationCacheStore) EXPECT() *MockFeatureFlagEvaluationCacheStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFeatureFlagEvaluationCacheStore) Get(ctx context.Context, key string) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockFeatureFlagEvaluationCacheStoreMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFeatureFlagEvaluationCacheStore)(nil).Get), ctx, key)
}

// InvalidateAll mocks base method.
func (m *MockFeatureFlagEvaluationCacheStore) InvalidateAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAll indicates an expected call of InvalidateAll.
func (mr *MockFeatureFlagEvaluationCacheStoreMockRecorder) InvalidateAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAll", reflect.TypeOf((*MockFeatureFlagEvaluationCacheStore)(nil).InvalidateAll), ctx)
}

// InvalidateUser mocks base method.
func (m *MockFeatureFlagEvaluationCacheStore) InvalidateUser(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUser indicates an expected call of InvalidateUser.
func (mr *MockFeatureFlagEvaluationCacheStoreMockRecorder) InvalidateUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUser", reflect.TypeOf((*MockFeatureFlagEvaluationCacheStore)(nil).InvalidateUser), ctx, userID)
}

// Set mocks base method.
func (m *MockFeatureFlagEvaluationCacheStore) Set(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockFeatureFlagEvaluationCacheStoreMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockFeatureFlagEvaluationCacheStore)(nil).Set), ctx, key, value, ttl)
}
