// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/negative_lookup_cache.go
//
// Generated by this command:
//
//	mockgen -source internal/service/negative_lookup_cache.go -destination internal/service/gomock/mock_negative_lookup_cache.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockNegativeLookupCacheStore is a mock of NegativeLookupCacheStore interface.
type MockNegativeLookupCacheStore struct {
	ctrl     *gomock.Controller
	recorder *MockNegativeLookupCacheStoreMockRecorder
	isgomock struct{}
}

// MockNegativeLookupCacheStoreMockRecorder is the mock recorder for MockNegativeLookupCacheStore.
type MockNegativeLookupCacheStoreMockRecorder struct {
	mock *MockNegativeLookupCacheStore
}

// NewMockNegativeLookupCacheStore creates a new mock instance.
func NewMockNegativeLookupCacheStore(ctrl *gomock.Controller) *MockNegativeLookupCacheStore {
	mock := &MockNegativeLookupCacheStore{ctrl: ctrl}
	mock.recorder = &MockNegativeLookupCacheStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNegativeLookupCacheStore) EXPECT() *MockNegativeLookupCacheStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockNegativeLookupCacheStore) Get(ctx context.Context, namespace, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, namespace, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNegativeLookupCacheStoreMockRecorder) Get(ctx, namespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNegativeLookupCacheStore)(nil).Get), ctx, namespace, key)
}

// InvalidateNamespace mocks base method.
func (m *MockNegativeLookupCacheStore) InvalidateNamespace(ctx context.Context, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateNamespace", ctx, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateNamespace indicates an expected call of InvalidateNamespace.
func (mr *MockNegativeLookupCacheStoreMockRecorder) InvalidateNamespace(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateNamespace", reflect.TypeOf((*MockNegativeLookupCacheStore)(nil).InvalidateNamespace), ctx, namespace)
}

// Set mocks base method.
func (m *MockNegativeLookupCacheStore) Set(ctx context.Context, namespace, key string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, namespace, key, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockNegativeLookupCacheStoreMockRecorder) Set(ctx, namespace, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockNegativeLookupCacheStore)(nil).Set), ctx, namespace, key, ttl)
}
