// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/rbac_permission_cache_store.go
//
// Generated by this command:
//
//	mockgen -source internal/service/rbac_permission_cache_store.go -destination internal/service/gomock/mock_rbac_permission_cache_store.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRBACPermissionCacheStore is a mock of RBACPermissionCacheStore interface.
type MockRBACPermissionCacheStore struct {
	ctrl     *gomock.Controller
	recorder *MockRBACPermissionCacheStoreMockRecorder
	isgomock struct{}
}

// MockRBACPermissionCacheStoreMockRecorder is the mock recorder for MockRBACPermissionCacheStore.
type MockRBACPermissionCacheStoreMockRecorder struct {
	mock *MockRBACPermissionCacheStore
}

// NewMockRBACPermissionCacheStore creates a new mock instance.
func NewMockRBACPermissionCacheStore(ctrl *gomock.Controller) *MockRBACPermissionCacheStore {
	mock := &MockRBACPermissionCacheStore{ctrl: ctrl}
	mock.recorder = &MockRBACPermissionCacheStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBACPermissionCacheStore) EXPECT() *MockRBACPermissionCacheStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRBACPermissionCacheStore) Get(ctx context.Context, userID uint, sessionTokenID string) ([]string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, sessionTokenID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockRBACPermissionCacheStoreMockRecorder) Get(ctx, userID, sessionTokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRBACPermissionCacheStore)(nil).Get), ctx, userID, sessionTokenID)
}

// InvalidateAll mocks base method.
func (m *MockRBACPermissionCacheStore) InvalidateAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAll indicates an expected call of InvalidateAll.
func (mr *MockRBACPermissionCacheStoreMockRecorder) InvalidateAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAll", reflect.TypeOf((*MockRBACPermissionCacheStore)(nil).InvalidateAll), ctx)
}

// InvalidateUser mocks base method.
func (m *MockRBACPermissionCacheStore) InvalidateUser(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUser indicates an expected call of InvalidateUser.
func (mr *MockRBACPermissionCacheStoreMockRecorder) InvalidateUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUser", reflect.TypeOf((*MockRBACPermissionCacheStore)(nil).InvalidateUser), ctx, userID)
}

// Set mocks base method.
func (m *MockRBACPermissionCacheStore) Set(ctx context.Context, userID uint, sessionTokenID string, permissions []string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, userID, sessionTokenID, permissions, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRBACPermissionCacheStoreMockRecorder) Set(ctx, userID, sessionTokenID, permissions, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRBACPermissionCacheStore)(nil).Set), ctx, userID, sessionTokenID, permissions, ttl)
}
