// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/storage_service.go
//
// Generated by this command:
//
//	mockgen -source internal/service/storage_service.go -destination internal/service/gomock/mock_storage_service.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
	isgomock struct{}
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// DeleteAvatar mocks base method.
func (m *MockStorageService) DeleteAvatar(ctx context.Context, userID uint, objectKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, userID, objectKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockStorageServiceMockRecorder) DeleteAvatar(ctx, userID, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockStorageService)(nil).DeleteAvatar), ctx, userID, objectKey)
}

// GenerateAvatarURL mocks base method.
func (m *MockStorageService) GenerateAvatarURL(ctx context.Context, objectKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAvatarURL", ctx, objectKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAvatarURL indicates an expected call of GenerateAvatarURL.
func (mr *MockStorageServiceMockRecorder) GenerateAvatarURL(ctx, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAvatarURL", reflect.TypeOf((*MockStorageService)(nil).GenerateAvatarURL), ctx, objectKey)
}

// UploadAvatar mocks base method.
func (m *MockStorageService) UploadAvatar(ctx context.Context, userID uint, file io.Reader, fileSize int64, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, file, fileSize, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockStorageServiceMockRecorder) UploadAvatar(ctx, userID, file, fileSize, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockStorageService)(nil).UploadAvatar), ctx, userID, file, fileSize, contentType)
}
