// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/auth_abuse_guard.go
//
// Generated by this command:
//
//	mockgen -source internal/service/auth_abuse_guard.go -destination internal/service/gomock/mock_auth_abuse_guard.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	context "context"
	reflect "reflect"
	time "time"

	service "github.com/sandeepkv93/everything-backend-starter-kit/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthAbuseGuard is a mock of AuthAbuseGuard interface.
type MockAuthAbuseGuard struct {
	ctrl     *gomock.Controller
	recorder *MockAuthAbuseGuardMockRecorder
	isgomock struct{}
}

// MockAuthAbuseGuardMockRecorder is the mock recorder for MockAuthAbuseGuard.
type MockAuthAbuseGuardMockRecorder struct {
	mock *MockAuthAbuseGuard
}

// NewMockAuthAbuseGuard creates a new mock instance.
func NewMockAuthAbuseGuard(ctrl *gomock.Controller) *MockAuthAbuseGuard {
	mock := &MockAuthAbuseGuard{ctrl: ctrl}
	mock.recorder = &MockAuthAbuseGuardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthAbuseGuard) EXPECT() *MockAuthAbuseGuardMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockAuthAbuseGuard) Check(ctx context.Context, scope service.AuthAbuseScope, identity, ip string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, scope, identity, ip)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockAuthAbuseGuardMockRecorder) Check(ctx, scope, identity, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockAuthAbuseGuard)(nil).Check), ctx, scope, identity, ip)
}

// RegisterFailure mocks base method.
func (m *MockAuthAbuseGuard) RegisterFailure(ctx context.Context, scope service.AuthAbuseScope, identity, ip string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterFailure", ctx, scope, identity, ip)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterFailure indicates an expected call of RegisterFailure.
func (mr *MockAuthAbuseGuardMockRecorder) RegisterFailure(ctx, scope, identity, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterFailure", reflect.TypeOf((*MockAuthAbuseGuard)(nil).RegisterFailure), ctx, scope, identity, ip)
}

// Reset mocks base method.
func (m *MockAuthAbuseGuard) Reset(ctx context.Context, scope service.AuthAbuseScope, identity, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, scope, identity, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockAuthAbuseGuardMockRecorder) Reset(ctx, scope, identity, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockAuthAbuseGuard)(nil).Reset), ctx, scope, identity, ip)
}
