// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/idempotency_store.go
//
// Generated by this command:
//
//	mockgen -source internal/service/idempotency_store.go -destination internal/service/gomock/mock_idempotency_store.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	context "context"
	reflect "reflect"
	time "time"

	service "github.com/sandeepkv93/everything-backend-starter-kit/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockIdempotencyStore is a mock of IdempotencyStore interface.
type MockIdempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyStoreMockRecorder
	isgomock struct{}
}

// MockIdempotencyStoreMockRecorder is the mock recorder for MockIdempotencyStore.
type MockIdempotencyStoreMockRecorder struct {
	mock *MockIdempotencyStore
}

// NewMockIdempotencyStore creates a new mock instance.
func NewMockIdempotencyStore(ctrl *gomock.Controller) *MockIdempotencyStore {
	mock := &MockIdempotencyStore{ctrl: ctrl}
	mock.recorder = &MockIdempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyStore) EXPECT() *MockIdempotencyStoreMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockIdempotencyStore) Begin(ctx context.Context, scope, key, fingerprint string, ttl time.Duration) (service.IdempotencyBeginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, scope, key, fingerprint, ttl)
	ret0, _ := ret[0].(service.IdempotencyBeginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockIdempotencyStoreMockRecorder) Begin(ctx, scope, key, fingerprint, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockIdempotencyStore)(nil).Begin), ctx, scope, key, fingerprint, ttl)
}

// Complete mocks base method.
func (m *MockIdempotencyStore) Complete(ctx context.Context, scope, key, fingerprint string, response service.CachedHTTPResponse, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, scope, key, fingerprint, response, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockIdempotencyStoreMockRecorder) Complete(ctx, scope, key, fingerprint, response, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockIdempotencyStore)(nil).Complete), ctx, scope, key, fingerprint, response, ttl)
}
