// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/admin_list_cache.go
//
// Generated by this command:
//
//	mockgen -source internal/service/admin_list_cache.go -destination internal/service/gomock/mock_admin_list_cache.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAdminListCacheStore is a mock of AdminListCacheStore interface.
type MockAdminListCacheStore struct {
	ctrl     *gomock.Controller
	recorder *MockAdminListCacheStoreMockRecorder
	isgomock struct{}
}

// MockAdminListCacheStoreMockRecorder is the mock recorder for MockAdminListCacheStore.
type MockAdminListCacheStoreMockRecorder struct {
	mock *MockAdminListCacheStore
}

// NewMockAdminListCacheStore creates a new mock instance.
func NewMockAdminListCacheStore(ctrl *gomock.Controller) *MockAdminListCacheStore {
	mock := &MockAdminListCacheStore{ctrl: ctrl}
	mock.recorder = &MockAdminListCacheStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminListCacheStore) EXPECT() *MockAdminListCacheStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAdminListCacheStore) Get(ctx context.Context, namespace, key string) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, namespace, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockAdminListCacheStoreMockRecorder) Get(ctx, namespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdminListCacheStore)(nil).Get), ctx, namespace, key)
}

// InvalidateNamespace mocks base method.
func (m *MockAdminListCacheStore) InvalidateNamespace(ctx context.Context, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateNamespace", ctx, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateNamespace indicates an expected call of InvalidateNamespace.
func (mr *MockAdminListCacheStoreMockRecorder) InvalidateNamespace(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateNamespace", reflect.TypeOf((*MockAdminListCacheStore)(nil).InvalidateNamespace), ctx, namespace)
}

// Set mocks base method.
func (m *MockAdminListCacheStore) Set(ctx context.Context, namespace, key string, value []byte, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, namespace, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockAdminListCacheStoreMockRecorder) Set(ctx, namespace, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockAdminListCacheStore)(nil).Set), ctx, namespace, key, value, ttl)
}

// MockAdminListCacheStoreWithAge is a mock of AdminListCacheStoreWithAge interface.
type MockAdminListCacheStoreWithAge struct {
	ctrl     *gomock.Controller
	recorder *MockAdminListCacheStoreWithAgeMockRecorder
	isgomock struct{}
}

// MockAdminListCacheStoreWithAgeMockRecorder is the mock recorder for MockAdminListCacheStoreWithAge.
type MockAdminListCacheStoreWithAgeMockRecorder struct {
	mock *MockAdminListCacheStoreWithAge
}

// NewMockAdminListCacheStoreWithAge creates a new mock instance.
func NewMockAdminListCacheStoreWithAge(ctrl *gomock.Controller) *MockAdminListCacheStoreWithAge {
	mock := &MockAdminListCacheStoreWithAge{ctrl: ctrl}
	mock.recorder = &MockAdminListCacheStoreWithAgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminListCacheStoreWithAge) EXPECT() *MockAdminListCacheStoreWithAgeMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAdminListCacheStoreWithAge) Get(ctx context.Context, namespace, key string) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, namespace, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockAdminListCacheStoreWithAgeMockRecorder) Get(ctx, namespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdminListCacheStoreWithAge)(nil).Get), ctx, namespace, key)
}

// GetWithAge mocks base method.
func (m *MockAdminListCacheStoreWithAge) GetWithAge(ctx context.Context, namespace, key string) ([]byte, bool, time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithAge", ctx, namespace, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(time.Duration)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetWithAge indicates an expected call of GetWithAge.
func (mr *MockAdminListCacheStoreWithAgeMockRecorder) GetWithAge(ctx, namespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithAge", reflect.TypeOf((*MockAdminListCacheStoreWithAge)(nil).GetWithAge), ctx, namespace, key)
}

// InvalidateNamespace mocks base method.
func (m *MockAdminListCacheStoreWithAge) InvalidateNamespace(ctx context.Context, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateNamespace", ctx, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateNamespace indicates an expected call of InvalidateNamespace.
func (mr *MockAdminListCacheStoreWithAgeMockRecorder) InvalidateNamespace(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateNamespace", reflect.TypeOf((*MockAdminListCacheStoreWithAge)(nil).InvalidateNamespace), ctx, namespace)
}

// Set mocks base method.
func (m *MockAdminListCacheStoreWithAge) Set(ctx context.Context, namespace, key string, value []byte, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, namespace, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockAdminListCacheStoreWithAgeMockRecorder) Set(ctx, namespace, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockAdminListCacheStoreWithAge)(nil).Set), ctx, namespace, key, value, ttl)
}
