// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/email_verification_notifier.go
//
// Generated by this command:
//
//	mockgen -source internal/service/email_verification_notifier.go -destination internal/service/gomock/mock_email_verification_notifier.go -package gomock
//

// Package gomock is a generated GoMock package.
package gomock

import (
	context "context"
	reflect "reflect"

	service "github.com/sandeepkv93/everything-backend-starter-kit/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailVerificationNotifier is a mock of EmailVerificationNotifier interface.
type MockEmailVerificationNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationNotifierMockRecorder
	isgomock struct{}
}

// MockEmailVerificationNotifierMockRecorder is the mock recorder for MockEmailVerificationNotifier.
type MockEmailVerificationNotifierMockRecorder struct {
	mock *MockEmailVerificationNotifier
}

// NewMockEmailVerificationNotifier creates a new mock instance.
func NewMockEmailVerificationNotifier(ctrl *gomock.Controller) *MockEmailVerificationNotifier {
	mock := &MockEmailVerificationNotifier{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationNotifier) EXPECT() *MockEmailVerificationNotifierMockRecorder {
	return m.recorder
}

// SendEmailVerification mocks base method.
func (m *MockEmailVerificationNotifier) SendEmailVerification(ctx context.Context, notification service.VerificationNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailVerification", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailVerification indicates an expected call of SendEmailVerification.
func (mr *MockEmailVerificationNotifierMockRecorder) SendEmailVerification(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailVerification", reflect.TypeOf((*MockEmailVerificationNotifier)(nil).SendEmailVerification), ctx, notification)
}

// MockPasswordResetNotifier is a mock of PasswordResetNotifier interface.
type MockPasswordResetNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetNotifierMockRecorder
	isgomock struct{}
}

// MockPasswordResetNotifierMockRecorder is the mock recorder for MockPasswordResetNotifier.
type MockPasswordResetNotifierMockRecorder struct {
	mock *MockPasswordResetNotifier
}

// NewMockPasswordResetNotifier creates a new mock instance.
func NewMockPasswordResetNotifier(ctrl *gomock.Controller) *MockPasswordResetNotifier {
	mock := &MockPasswordResetNotifier{ctrl: ctrl}
	mock.recorder = &MockPasswordResetNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetNotifier) EXPECT() *MockPasswordResetNotifierMockRecorder {
	return m.recorder
}

// SendPasswordReset mocks base method.
func (m *MockPasswordResetNotifier) SendPasswordReset(ctx context.Context, notification service.PasswordResetNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordReset", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordReset indicates an expected call of SendPasswordReset.
func (mr *MockPasswordResetNotifierMockRecorder) SendPasswordReset(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordReset", reflect.TypeOf((*MockPasswordResetNotifier)(nil).SendPasswordReset), ctx, notification)
}
